[package]
name = "cop_dag"
version = "0.0.1"
edition = "2018"
publish = false
description = "TiKV Coprocessor DAG"

[dependencies]
hex = "0.3"
byteorder = "1.2"
tikv_util = { path = "../tikv_util" }
cop_datatype = {path = "../cop_datatype"}
log_wrappers = { path = "../log_wrappers" }
kvproto = { git = "https://github.com/pingcap/kvproto.git" }
tipb = { git = "https://github.com/pingcap/tipb.git" }
quick-error = "1.2.2"
smallvec = { version = "0.6", features = ["union"] }
chrono = "0.4"
chrono-tz = "0.5"
regex = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
num = { version = "0.2", default-features = false }
num-traits = "0.2"
bitflags = "1.0.1"
rust-crypto = "^0.2"
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
crc = "1.8"
rand = "0.3"
time = "0.1"
base64 = "0.10"
safemem = { version = "0.3", default-features = false }
log = { version = "0.3", features = ["max_level_trace", "release_max_level_debug"] }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-async = { version = "2.3", default-features = false }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "91904ade" }
slog-term = "2.4"
slog_derive = "0.1"
protobuf = "~2.0"
twoway = "0.2.0"
lazy_static = "0.2.1"
fail = "0.2"

[dependencies.prometheus]
version = "0.4.2"
default-features = false
features = ["nightly", "push", "process"]